// UK free-to-air broadcaster for each World Cup 2026 fixture (BBC vs ITV).
// API-Football carries no UK TV data, so this is a manual map sourced from the published
// BBC/ITV schedule (live-footballontv.com + ESPN UK TV guide). Keyed by the two team ids sorted
// + joined with "|" so home/away order doesn't matter. All 72 group-stage fixtures and the 16
// Round-of-32 ties are covered; later knockout ties show no badge until added here.
export type Broadcaster = "BBC" | "ITV";

const BROADCASTERS: Record<string, Broadcaster> = {
  "algeria|argentina": "ITV",
  "algeria|austria": "BBC",
  "algeria|jordan": "ITV",
  "argentina|austria": "BBC",
  "argentina|jordan": "BBC",
  "australia|paraguay": "ITV",
  "australia|turkiye": "ITV",
  "australia|usa": "BBC",
  "austria|jordan": "BBC",
  "belgium|egypt": "BBC",
  "belgium|iran": "ITV",
  "belgium|new-zealand": "BBC",
  "bosnia-and-herzegovina|canada": "BBC",
  "bosnia-and-herzegovina|qatar": "ITV",
  "bosnia-and-herzegovina|switzerland": "ITV",
  "brazil|haiti": "ITV",
  "brazil|morocco": "BBC",
  "brazil|scotland": "BBC",
  "canada|qatar": "ITV",
  "canada|switzerland": "ITV",
  "cape-verde-islands|saudi-arabia": "ITV",
  "cape-verde-islands|spain": "ITV",
  "cape-verde-islands|uruguay": "BBC",
  "colombia|congo-dr": "ITV",
  "colombia|portugal": "BBC",
  "colombia|uzbekistan": "BBC",
  "congo-dr|portugal": "BBC",
  "congo-dr|uzbekistan": "BBC",
  "croatia|england": "ITV",
  "croatia|ghana": "ITV",
  "croatia|panama": "BBC",
  "curacao|ecuador": "BBC",
  "curacao|germany": "ITV",
  "curacao|ivory-coast": "BBC",
  "czechia|mexico": "BBC",
  "czechia|south-africa": "BBC",
  "czechia|south-korea": "ITV",
  "ecuador|germany": "BBC",
  "ecuador|ivory-coast": "BBC",
  "egypt|iran": "BBC",
  "egypt|new-zealand": "ITV",
  "england|ghana": "BBC",
  "england|panama": "ITV",
  "france|iraq": "BBC",
  "france|norway": "ITV",
  "france|senegal": "BBC",
  "germany|ivory-coast": "ITV",
  "ghana|panama": "ITV",
  "haiti|morocco": "BBC",
  "haiti|scotland": "BBC",
  "iran|new-zealand": "BBC",
  "iraq|norway": "BBC",
  "iraq|senegal": "ITV",
  "japan|netherlands": "ITV",
  "japan|sweden": "BBC",
  "japan|tunisia": "BBC",
  "mexico|south-africa": "ITV",
  "mexico|south-korea": "BBC",
  "morocco|scotland": "ITV",
  "netherlands|sweden": "BBC",
  "netherlands|tunisia": "BBC",
  "norway|senegal": "ITV",
  "paraguay|turkiye": "ITV",
  "paraguay|usa": "BBC",
  "portugal|uzbekistan": "ITV",
  "qatar|switzerland": "ITV",
  "saudi-arabia|spain": "BBC",
  "saudi-arabia|uruguay": "ITV",
  "south-africa|south-korea": "BBC",
  "spain|uruguay": "ITV",
  "sweden|tunisia": "ITV",
  "turkiye|usa": "ITV",

  // Round of 32 (BBC/ITV split as published).
  "canada|south-africa": "ITV",
  "brazil|japan": "ITV",
  "germany|paraguay": "BBC",
  "morocco|netherlands": "ITV",
  "ivory-coast|norway": "BBC",
  "france|sweden": "ITV",
  "ecuador|mexico": "ITV",
  "congo-dr|england": "BBC",
  "belgium|senegal": "ITV",
  "bosnia-and-herzegovina|usa": "BBC",
  "austria|spain": "BBC",
  "croatia|portugal": "BBC",
  "algeria|switzerland": "BBC",
  "australia|egypt": "BBC",
  "argentina|cape-verde-islands": "ITV",
  "colombia|ghana": "ITV",
};

/** UK broadcaster for a fixture, or null if not yet confirmed. */
export function broadcasterFor(homeTeamId: string, awayTeamId: string): Broadcaster | null {
  return BROADCASTERS[[homeTeamId, awayTeamId].sort().join("|")] ?? null;
}
